#!/bin/bash

set -xe

./script/gen-calendar

mv events.ics static

cd cljcalendar/
./build.sh
rm -fr ../static/calendar
mv build ../static/calendar

export TZ=America/Chicago
hugo \
  --gc \
  --minify \
  --baseURL "${BASE_URL:-https://madclj.com}/"
