#!/bin/bash

set -xe

export TZ=America/Chicago

./script/gen-calendar

mv events.ics static

cd madcalendar/
npm install
npm run build
rm -fr ../static/calendar
mv build ../static/calendar

cd ..
hugo \
  --gc \
  --minify \
  --baseURL "${BASE_URL:-https://madclj.com}/"
